name: "Deploy on PR Merge to Main"

on:
  pull_request:
    branches:
      - main

env:
  APP_NAME: "472-be-cicd"
  DOCKER_IMAGE: "${{ secrets.DOCKERHUB_USERNAME }}/472-be-cicd"

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Determine new tag"
        id: get_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          NEW_TAG=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      - name: "Build and push container"
        run: |-
          IMAGE_NAME="${{ env.DOCKER_IMAGE }}:${{ env.NEW_TAG }}"
          docker build -f docker/prod.Dockerfile -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"

      - name: "Create GitHub Release and Tag"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          generate_release_notes: true
