name: "Develop to main branch Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ secrets.GO_VERSION }}

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Docker Image
        # run: docker build -t ampqq/472-be-cicd:latest .
        run: docker build -t ampqq/472-be-cicd:latest -f docker/dev.Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docke Hub
        run: |
          docker tag ampqq/472-be-cicd:latest ampqq/472-be-cicd:$(date +%Y.%m.%d-%H%M%S)
          docker push ampqq/472-be-cicd:latest
          docker push ampqq/472-be-cicd:$(date +%Y.%m.%d-%H%M%S)

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/chechout@v4

      - name: Generate Version Tag
        id: tag
        run: |
          VERSION=$(git describe --tags --abbrev=0)

          VERSION_NUMBER=$(echo $VERSION | sed 's/v//g')

          IFS='.' read -r major minor patch <<< "$VERSION_NUMBER"
          patch=$((patch + 1))

          NEW_TAG="$major.$minor.$patch"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          draft: false
          prerelease: false

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag ampqq/472-be-cicd:latest ampqq/472-be-cicd:${{ env.NEW_TAG }}

          docker push ampqq/472-be-cicd:latest
          docker push ampqq/472-be-cicd:${{ env.NEW_TAG }}
