name: "Develop to main branch Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ secrets.GO_VERSION }}

      - name: Install Dependencies
        run: go mod tidy

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/472-be-cicd"
          TAG=$(date +%Y.%m.%d-%H%M%S)

          docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$TAG" -f docker/dev.Dockerfile .
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:$TAG"

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Version Tag
        id: tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          VERSION_NUMBER=$(echo $LATEST_TAG | sed 's/v//g')

          IFS='.' read -r major minor patch <<< "$VERSION_NUMBER"
          patch=$((patch + 1))
          NEW_TAG="v$major.$minor.$patch"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          draft: false
          prerelease: false

      - name: Push Docker Image with New Tag
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/472-be-cicd"

          docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:${{ env.NEW_TAG }}"
          docker push "$IMAGE_NAME:${{ env.NEW_TAG }}"
